// petdex extension for OMP (Oh My Pi). Auto-generated by the Petdex
// desktop app's Agents panel.
//
// OMP has no shell-command hooks: its docs call that subsystem legacy and
// point at an in-process extension API instead, so this is a module OMP
// loads rather than a config file we edit. Everything below is typed
// against packages/coding-agent/src/extensibility/extensions/types.ts at
// can1357/oh-my-pi.
//
// Each pi.on handler below maps one OMP event to one mascot state; edit
// the state strings there to change what the pet does.

import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

const HOOK_SERVER_URL = "http://127.0.0.1:7777/state";
const HOOK_SERVER_BUBBLE_URL = "http://127.0.0.1:7777/bubble";
const RUNTIME_DIR = join(homedir(), ".petdex", "runtime");
const TOKEN_PATH = join(RUNTIME_DIR, "update-token");
const KILLSWITCH_PATH = join(RUNTIME_DIR, "hooks-disabled");
const AGENT_SOURCE = "omp";

// Read-only tools read as thinking rather than working, matching how the
// other adapters split `review` from `running`.
const REVIEW_TOOLS = new Set(["read", "grep", "glob", "list", "search"]);

async function readToken(): Promise<string | null> {
  try {
    return (await readFile(TOKEN_PATH, "utf8")).trim();
  } catch {
    return null;
  }
}

async function postJson(
  url: string,
  body: Record<string, unknown>,
  token: string,
): Promise<void> {
  try {
    await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Petdex-Update-Token": token,
      },
      body: JSON.stringify(body),
      // 300ms instead of 1s: well above any real localhost roundtrip and
      // below the threshold an agent user notices as latency. Extensions
      // share OMP's process, so a hung request would stall the agent.
      signal: AbortSignal.timeout(300),
    });
  } catch {
    // Hook server offline: stay quiet, the agent should not notice.
  }
}

type Notify = {
  state: string;
  duration?: number;
  text?: string;
  title?: string;
  busy?: boolean;
  sessionId?: string | null;
};

type ExtensionContext = {
  sessionManager?: {
    getSessionId?: () => string | null | undefined;
  };
  ui: { notify(message: string, type?: string): void };
};

type SessionEvent = { sessionId?: unknown };

function sessionIdFor(
  ctx: ExtensionContext | undefined,
  event?: SessionEvent,
): string | null {
  const eventSession = event?.sessionId;
  if (typeof eventSession === "string" && eventSession.length > 0) {
    return eventSession;
  }
  const contextSession = ctx?.sessionManager?.getSessionId?.();
  return typeof contextSession === "string" && contextSession.length > 0
    ? contextSession
    : null;
}

async function notify({
  state,
  duration,
  text,
  title,
  busy,
  sessionId,
}: Notify): Promise<void> {
  // Killswitch first, before the token read, so the disabled state costs
  // one existsSync and nothing else.
  if (existsSync(KILLSWITCH_PATH)) return;
  const token = await readToken();
  if (!token) return; // Hook server offline or missing; silently no-op.
  const stateBody: Record<string, unknown> =
    duration != null
      ? { state, duration, agent_source: AGENT_SOURCE }
      : { state, agent_source: AGENT_SOURCE };
  const bubbleBody: Record<string, unknown> = {
    text,
    agent_source: AGENT_SOURCE,
    agent_state: state,
  };
  if (sessionId) {
    stateBody.session_id = sessionId;
    bubbleBody.session_id = sessionId;
  }
  if (title) bubbleBody.title = title;
  if (busy !== undefined) bubbleBody.busy = busy;
  await Promise.all([
    postJson(HOOK_SERVER_URL, stateBody, token),
    text
      ? postJson(HOOK_SERVER_BUBBLE_URL, bubbleBody, token)
      : Promise.resolve(),
  ]);
}

function clip(value: string, max: number): string {
  const flat = value.replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat;
}

/** A short label for what a tool call is doing, for the bubble text. */
function describeTool(
  toolName: string,
  input: Record<string, unknown>,
  done: boolean,
): string {
  const field = (key: string): string | null => {
    const value = input?.[key];
    return typeof value === "string" && value.length > 0 ? value : null;
  };
  switch (toolName) {
    case "bash": {
      const command = field("command");
      return command
        ? `${done ? "Ran" : "Running"} ${clip(command, 28)}`
        : done
          ? "Ran a command"
          : "Running a command";
    }
    case "read":
      return `${done ? "Read" : "Reading"} ${clip(field("file_path") ?? field("path") ?? "a file", 28)}`;
    case "write":
    case "edit":
      return `${done ? "Edited" : "Editing"} ${clip(field("file_path") ?? field("path") ?? "a file", 28)}`;
    case "grep": {
      const pattern = field("pattern");
      // Typographic quotes, not ASCII: the hook server reads the bubble body
      // back with a scanner that stops at a bare quote (#628).
      return pattern
        ? `${done ? "Searched" : "Searching"} “${clip(pattern, 24)}”`
        : done
          ? "Searched files"
          : "Searching files";
    }
    default:
      return `${done ? "Ran" : "Running"} ${clip(toolName, 28)}`;
  }
}

// Minimal structural types. Importing OMP's own would couple the
// generated file to a package path that varies by install, and these are
// the only fields read. Kept in sync with
// packages/coding-agent/src/extensibility/extensions/types.ts.
type ToolCallEvent = { toolName: string; input?: Record<string, unknown> };
type ToolResultEvent = {
  toolName: string;
  input?: Record<string, unknown>;
  isError: boolean;
};
type InputEvent = { text: string };
type AgentEndEvent = {
  willContinue?: boolean;
  messages?: Array<{ role?: string; stopReason?: string }>;
};

type ExtensionAPI = {
  on(
    event: string,
    handler: (event: never, ctx: ExtensionContext) => unknown,
  ): void;
  registerCommand(
    name: string,
    options: {
      description?: string;
      handler: (
        args: string,
        ctx: { ui: { notify(message: string, type?: string): void } },
      ) => Promise<void>;
    },
  ): void;
};

export default function petdex(pi: ExtensionAPI): void {
  const prompts = new Map<string, string>();
  const promptKey = (sessionId: string | null): string => sessionId ?? "";
  const titleFor = (sessionId: string | null): string | undefined =>
    prompts.get(promptKey(sessionId));

  pi.on("session_start", (async (_event, ctx) => {
    await notify({
      state: "jumping",
      duration: 1200,
      busy: false,
      sessionId: sessionIdFor(ctx),
    });
  }) as never);

  pi.on("input", (async (event: InputEvent, ctx) => {
    // `text` is a plain string here, unlike Kimi Code's ContentPart[].
    const sessionId = sessionIdFor(ctx);
    const prompt = typeof event?.text === "string" ? clip(event.text, 60) : "";
    if (prompt) prompts.set(promptKey(sessionId), prompt);
    await notify({
      state: "jumping",
      duration: 900,
      text: "Thinking…",
      title: titleFor(sessionId),
      busy: true,
      sessionId,
    });
  }) as never);

  pi.on("tool_call", (async (event: ToolCallEvent, ctx) => {
    const name = event?.toolName ?? "";
    const sessionId = sessionIdFor(ctx);
    await notify({
      state: REVIEW_TOOLS.has(name) ? "review" : "running",
      text: describeTool(name, event?.input ?? {}, false),
      title: titleFor(sessionId),
      busy: true,
      sessionId,
    });
  }) as never);

  pi.on("tool_result", (async (event: ToolResultEvent, ctx) => {
    // `isError` is on the payload, set true before the error is rethrown,
    // so failure is a real signal here rather than something inferred
    // from result text the way CodeBuddy forces.
    const sessionId = sessionIdFor(ctx);
    if (event?.isError) {
      await notify({
        state: "failed",
        duration: 2500,
        text: `${describeTool(event?.toolName ?? "", event?.input ?? {}, true)} failed`,
        title: titleFor(sessionId),
        busy: true,
        sessionId,
      });
      return;
    }
    await notify({
      state: "idle",
      text: describeTool(event?.toolName ?? "", event?.input ?? {}, true),
      title: titleFor(sessionId),
      busy: true,
      sessionId,
    });
  }) as never);

  pi.on("tool_approval_requested", (async (event: SessionEvent, ctx) => {
    const sessionId = sessionIdFor(ctx, event);
    await notify({
      state: "waiting",
      text: "Waiting on you.",
      title: titleFor(sessionId),
      busy: false,
      sessionId,
    });
  }) as never);

  pi.on("tool_approval_resolved", (async (event: SessionEvent, ctx) => {
    const sessionId = sessionIdFor(ctx, event);
    await notify({
      state: "running",
      text: "Continuing…",
      title: titleFor(sessionId),
      busy: true,
      sessionId,
    });
  }) as never);

  pi.on("agent_end", (async (event: AgentEndEvent, ctx) => {
    const sessionId = sessionIdFor(ctx);
    // OMP explicitly marks retries/continuations as non-terminal. A failed
    // request scheduled to retry must not produce a misleading Done bubble.
    if (event?.willContinue) {
      await notify({
        state: "running",
        text: "Continuing…",
        title: titleFor(sessionId),
        busy: true,
        sessionId,
      });
      return;
    }
    const reason = Array.isArray(event?.messages)
      ? event.messages.findLast((message) => message?.role === "assistant")
          ?.stopReason
      : undefined;
    await notify({
      state:
        reason === "error"
          ? "failed"
          : reason === "aborted"
            ? "idle"
            : "waving",
      duration: 1500,
      text:
        reason === "error"
          ? "Stopped with an error"
          : reason === "aborted"
            ? "Cancelled."
            : "Done.",
      title: titleFor(sessionId),
      busy: false,
      sessionId,
    });
  }) as never);

  pi.on("session_shutdown", (async (_event, ctx) => {
    const sessionId = sessionIdFor(ctx);
    await notify({
      state: "idle",
      text: "Session ended.",
      busy: false,
      sessionId,
    });
    prompts.delete(promptKey(sessionId));
  }) as never);

  pi.registerCommand("petdex", {
    description: "Show whether the Petdex mascot is connected",
    handler: async (_args, ctx) => {
      if (existsSync(KILLSWITCH_PATH)) {
        ctx.ui.notify("Petdex hooks are disabled (killswitch on).", "warning");
        return;
      }
      const token = await readToken();
      ctx.ui.notify(
        token
          ? "Petdex is connected."
          : "Petdex Desktop is not running (no hook server token).",
        token ? "info" : "warning",
      );
    },
  });
}
