import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const result = await Bun.build({
  entrypoints: [
    fileURLToPath(new URL("packages/petdex-cli/bin/petdex-mcp.ts", root)),
  ],
  target: "node",
  minify: false,
});
if (!result.success) throw new Error(result.logs.join("\n"));
const output =
  "// Generated by bun scripts/build-petdex-mcp.ts. Do not edit.\n" +
  (await result.outputs[0].text());
const dest = new URL(
  "packages/petdex-desktop-native/src/assets/petdex-mcp-server.mjs",
  root,
);
if (process.argv.includes("--check")) {
  if ((await Bun.file(dest).text()) !== output)
    throw new Error(
      "Desktop MCP asset is stale; run bun scripts/build-petdex-mcp.ts",
    );
} else await Bun.write(dest, output);
